### ISSUE TITLE
Style remark : using 2 spaces tabs

### ISSUE THREAD

**Issue by rom1504** [Minecheesecraft/Cheese-Bot#2]
I think using 2-space tabs produce a more readable code (different editors use different space size for the tab character, and in some it's particularly unreadable (in github for example))

Compare the readability of https://github.com/Minecheesecraft/Cheese-Bot/blob/master/src/scripts/botcore.js#L22 vs https://github.com/Minecheesecraft/Cheese-Bot/blob/master/src/scripts/botcore.js#L47

2-space tabs is the rules used in mineflayer (and other prismarinejs projects), and many other js projects

As this is a new project, you might be interested in following http://standardjs.com/#rules even though I think following the 2-space rule is generally enough.

**Comment by Ezcha** [comment]
Fixed it!
