### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by yunfan** [Minecheesecraft/Cheese-Bot#5]
sorry i am not familliar with nodejs, and i havnt saw any documents about this

would you please add some usage sample?

**Comment by Ezcha** [comment]
This project is no longer updated and will not work with recent versions of Minecraft. I am making a a completely reworked version that will have proper documentation.

**Comment by yunfan** [comment]
@Ezcha so where is the new project ? want to have a try when its available

**Comment by Ezcha** [comment]
@yunfan It's not released yet, but will be soon.

**Comment by ramdan1523** [comment]
Is it released now?

**Comment by Wuemeli** [comment]
Brah
